name: bloc_vs_riverpod_example
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  flutter_riverpod: ^1.0.3
  connectivity_plus: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  bloc_test: ^9.0.2
  state_notifier_test: ^0.0.4
  mockito: ^5.0.17
  build_runner: ^2.1.7

flutter:
  uses-material-design: true
